# Generated by Django 5.2.10 on 2026-01-10 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ads/', verbose_name='Фото'),
        ),
    ]
