# Generated by Django 5.2.10 on 2026-01-18 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_adimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='image',
        ),
    ]
