# Generated by Django 5.2.10 on 2026-03-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_ad_expires_at_profile_avatar_alter_profile_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='is_promoted',
        ),
        migrations.AddField(
            model_name='ad',
            name='category',
            field=models.CharField(choices=[('phones', 'Телефоны'), ('laptops', 'Ноутбуки'), ('games', 'Игры'), ('cars', 'Авто'), ('clothes', 'Одежда'), ('other', 'Другое')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='ad',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ads/'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
