# Generated by Django 5.2.10 on 2026-03-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0011_remove_message_receiver_alter_message_sender_chat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
