# Generated by Django 5.2.10 on 2026-03-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0014_remove_message_image_alter_message_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
