# Generated by Django 5.2.10 on 2026-04-11 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0018_ad_condition_ad_memory_ad_mileage_ad_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='condition',
        ),
        migrations.AddField(
            model_name='ad',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='drive',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='engine',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='power',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='transmission',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='wheel',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
