# Generated by Django 5.2.10 on 2026-04-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0019_remove_ad_condition_ad_color_ad_drive_ad_engine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='is_promoted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ad',
            name='promoted_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
