# Generated by Django 5.2.10 on 2026-04-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0020_ad_is_promoted_ad_promoted_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='promoted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='promotion_level',
            field=models.IntegerField(default=0),
        ),
    ]
