# Generated by Django 5.2.10 on 2026-05-28 19:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0023_remove_payment_order_id_payment_external_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['is_published', '-created_at'], name='ads_ad_is_publ_e11b24_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['is_published', 'price'], name='ads_ad_is_publ_42adbe_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['is_published', '-views'], name='ads_ad_is_publ_611609_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['promoted_until'], name='ads_ad_promote_d78780_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['city'], name='ads_ad_city_865388_idx'),
        ),
    ]
